- ##### social_core.exceptions.AuthAlreadyAssociated: This account is already in use.
  * https://stackoverflow.com/questions/13018147/authalreadyassociated-exception-in-django-social-auth